apiVersion: apps/v1
kind: Deployment
metadata:
  name: arguswarm-overseer
  namespace: arguswarm
  labels:
    app: arguswarm-overseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arguswarm-overseer
  template:
    metadata:
      labels:
        app: arguswarm-overseer
    spec:
      serviceAccountName: arguswarm-overseer
      containers:
        - name: overseer
          image: hibare/arguswarm:latest
          command: ["arguswarm", "overseer"]
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ARGUSWARM_PROVIDER
              value: "kubernetes"
          envFrom:
            - configMapRef:
                name: arguswarm-config
            - secretRef:
                name: arguswarm-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: arguswarm-overseer
  namespace: arguswarm
  labels:
    app: arguswarm-overseer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: arguswarm-overseer
